name: Event Reminders

on:
  workflow_dispatch:

jobs:
  event-reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile

      - run: node src/event-reminder.js
        env:
          SPACE_JELLY_TWITTER_CONSUMER_KEY: ${{ secrets.SPACE_JELLY_TWITTER_CONSUMER_KEY }}
          SPACE_JELLY_TWITTER_CONSUMER_SECRET: ${{ secrets.SPACE_JELLY_TWITTER_CONSUMER_SECRET }}
          SPACE_JELLY_TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.SPACE_JELLY_TWITTER_ACCESS_TOKEN_KEY }}
          SPACE_JELLY_TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.SPACE_JELLY_TWITTER_ACCESS_TOKEN_SECRET }}
