name: Printer Refresh

on:
  schedule:
    - cron: "0 23 * * 0"
  workflow_dispatch:

jobs:
  printer-refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --frozen-lockfile

      - run: node src/printer-refresh.js
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          PRINTER_REFRESH_MAIL_TO: ${{ secrets.PRINTER_REFRESH_MAIL_TO }}
          PRINTER_REFRESH_MAIL_FROM: ${{ secrets.PRINTER_REFRESH_MAIL_FROM }}
