name: SSL Check

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 22

      - run: npm install

      - run: node src/ssl-check.js
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          SSL_HOSTS: ${{ secrets.SSL_HOSTS }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}